name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wildfly
        uses: actions/checkout@v2
      - name: Checkout wildfly-core
        uses: actions/checkout@v2
        with:
          repository: predkambrij/wildfly-core
          branch: gh_12.0.3.Final
      - name: Build project
        id: dockerstep
        uses: ./builddir/

      - name: Prepare vars
        id: prepare_vars
        shell: bash
        run: |
          echo ::set-output name=time::$(date +%s)
          echo ::set-output name=gitbranchname::${GITHUB_REF:11} #GITHUB_REF=refs/heads/<branchname>
          echo ::set-output name=gitsha::${GITHUB_SHA}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}${{ steps.prepare_vars.outputs.time }}
          release_name: Release ${{ github.ref }}${{ steps.prepare_vars.outputs.time }}
          body: |
            Generated by actions
            - time ${{ steps.prepare_vars.outputs.time }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifact.zip
          asset_name: artifact_${{ steps.prepare_vars.outputs.gitbranchname }}_${{ steps.prepare_vars.outputs.time }}_${{ steps.prepare_vars.outputs.gitsha }}.zip
          asset_content_type: application/zip


